### ISSUE TITLE
Links to references week 1

### ISSUE THREAD

**Issue by MFloru** [ikerito7/Bacchus-R1#2]
In this issue we will track all the references we think will be useful for our project. Not to overload GIT, we only provide the link to the documents.
Every post needs to look like this;

Title of the reference
Short description of the topic and why you believe it is useful.
The link to the article

**Comment by MFloru** [comment]
Edible insects
Future prospects for food and feed security

This is the most comprehensive report on the insect for food industry available right now. It is the standard work that everybody of us should read.

http://www.fao.org/docrep/018/i3253e/i3253e00.htm

**Comment by MFloru** [comment]
Dionysus
Encyclopedica mythica citing Dionysus as the god of agriculture and the fertility of nature
http://www.pantheon.org/articles/d/dionysus.html

Theoi Dyonisos
BEst reference to this god
http://www.theoi.com/Olympios/Dionysos.html

**Comment by melindatjia** [comment]
Edible forest insect
this link has more than one articles, in general discussing about the region where insect is commonly found as food, group of insect that commonly consumed, the adventages (from the nutrition point of view to the general point of view), the effect to the ecosystem, and the future prospect.
it's a little bit hard to find the government regulation towards insect consumption as consuming insect is not really a common thing in most of the country thus has a limited study. 
https://cisr.ucr.edu/pdf/edible-forest-inescts.pdf#page=10

**Comment by ikerito7** [comment]
Intersting article in English about the variety of insects that one can find solely in Mexico;

http://www.lonelyplanet.com/mexico/oaxaca-state/travel-tips-and-articles/the-10-tastiest-insects-and-bugs-in-mexico

**Comment by ghost** [comment]
Hi guys! I put the 3 reports I refer to in teambition, but also give the links.

As a contextualization 

Brief history of food sources (and therefore, processing) evolution
From hunting and gathering, Human went to agriculture (domestication of both animals and plants), hence the importance of food preservation.
[Former preservation techniques =sundrying, salting, smoking, fermentation, etc...]

Now is the age of the food industry, with new trends and techniques.
Western societies derive indeed 30 000 different products from about 6 staple food (rice, wheat, maize, barley oat and potato) whereas some hunting and gathering tribes use about 100 different sources of food.

Current preservation techniques: 
Physical (heat, freezing, deshydratation), chemical (pH, Redox potential, preservatives, CO2) or both.
In fact, what is interesting to know is that the moisture content of a food is linked to its length of preservation, so most of techniques aim at reducing this water food contain. However, reducing water in food enhances its energy density although nowadays, customers want fresher and lighter food.
This is a paradox to solve (preservation VS fresh-feeling)... And new technologies are been developed to address that issue

[Ref (9 pages) : http://journals.cambridge.org/download.php?file=%2FPNS%2FPNS56_03%2FS0029665197000463a.pdf&code=dd7003abddac5e9e3d961c531b3262e2

=> how to breed and process insects to preserve them? Is technology ready yet?

About the food market recent evolution http://www.un.org/en/globalissues/food/
 “For two decades, leading up to the millennium, global demand for food increased steadily, along with growth in the world’s population [doubled between 1960 and 2000; expected to reach more than 9 billion people by 2050], record harvests, improvements in incomes, and the diversification of diets.  As a result, food prices continued to decline through 2000.”
But price began to increase again because of higher demand than supply in 2004, followed by a drop of production because of bad weather, oil price increase and finally, states wanting to buy grains to prevent themselves from shortage. All that made grain market volatile and prices increase. Now they seem stabilizing
“prices are expected to remain high over the medium to long term with devastating consequences for the world’s most vulnerable populations. “
[The rest of the article explains what which organism will do and send to other links.]
=> aren’t insects a solution, if we can breed them for a little price? 

Food Prospects
ftp://ftp.fao.org/docrep/fao/004/y3557e/y3557e.pdf
Table of content on page 7 of the PDF
For figures, I recommend you “The projections at a glance” on page 9 (= pages 19-20 on the PDF)

I think you can have a quick look at the graphics (lots of them are provided in this doc), and potentially read the framed data in the text.
But they don’t talk about insects

“Global agricultural performance : past trends and future prospects”
http://siteresources.worldbank.org/INTWDRS/Resources/477365-1327599046334/8394679-1327599874257/Pingali-Global_Agricultural_Performance.pdf
[same as previously: you can quickly look through it reading titles and looking at graphs].

Basically it puts figures on what we know (or could guess) about the evolution of agricultural production.
Ex: Food consumption increased “from an average of 2280 kcal/person/day in the early 1960s to 2800 kcal/person/day today [=in 2008]”

Also points out the many disparities amongst the world, and even between countries in a same part of the world (like in Africa)

**Comment by MFloru** [comment]
Iker, I loved that article about the edible insects in Mexico ;)
I have something for you now 

Edible insect industry in the USA
This article gives the current size of the industry (20 million $ ) and lists different companies among the steps of the supply chain, so this can help you with finding the techniques they use to 'manufacture' insect food. Also, it states that cricket floor currently costs 30$/kg , that sounds like a price that asks for huge improvements in the processing steps!

http://www.fastcompany.com/3037716/inside-the-edible-insect-industrial-complex

**Comment by ikerito7** [comment]
Mathias, the article was very useful it gave me the names of the producers of bugs nowadays; here I share the company blog of Tiny Farm one of the largest producer of bugs; it has lots of interesting entries about the industry
http://www.tiny-farms.com/blog

**Comment by MFloru** [comment]
Yes I've seen that website as well : actually, they are consultants about the bug industry and clearly point out that lots of improvements need to be made in the supply chain. I guess they are still rather small and can use help, so what do you think of the following : 

We try to contact them and tell them we are students but our project aligns very well with their goals. 
Then we can ask them for an information exchange. For example, they can give us information about how the bug supply chain and processing works right now. We, with acces to that information can try to improve a part of it and then send the results of that project back to them.

That will, I believe, make our work way more serious and possibly useful for industry.
Let's talk about that tomorrow in class.

**Comment by MFloru** [comment]
Let's claim a free 'feed the world' insect T-shirt to wear on our final presentation ;)

the only thing we need to do is too blog/ post on social media about the company in this link.
And if we send them an e-mail and the 5 of us blog about it, I hope they want to ship the free t-shirts to China.

http://www.thefarmedinsectcompany.com/

**Comment by MFloru** [comment]
The website where we can claim the T shirt also offers lots of links and even links to some TED movies :D 
The following website lists another 5 companies currently working on insects:

http://www.fooddive.com/news/5-food-companies-betting-on-the-bug-business/152338/

AND NOW I FOUND IT : 

The next website, openbugfarm, is an open source platofrm hosted by tiny farms were everybody can contribute to share information about the breeding/rearing of insects. Also with kits of small scale bug farms, something we can make! blueprints and source code are shared on GITHUB and it is MAKER friendly. I believe this is exactly what our professor wants us to do!!!
http://www.openbugfarm.com/

**Comment by MFloru** [comment]
Europe - legislation

This article cites a Spanish bug producent and points out there are only 4 countries in Europe where there exists legislation about bugs. Among them, Belgium :D 

http://www.ipsnews.net/2013/07/edible-insect-market-hindered-by-legal-and-cultural-barriers-in-spain/

Another article citing start ups in the USA : 
http://fortune.com/2014/07/18/bugs-in-your-protein-bar-are-edible-insects-the-next-food-craze/

**Comment by ikerito7** [comment]
Risk of eating insects
A very interesting article about the risk of a bad handling in the insect growing industry. The breeding of insects for human consumption has to be tied with strict quality controls, as there is a lot of possible health issues involved. 

The article is in spanish so only me and Marie can understand it, but I will still post it as a reference that will be useful in the future. 
http://www.consumer.es/seguridad-alimentaria/sociedad-y-consumo/2015/02/18/221464.php

**Comment by ikerito7** [comment]
Good article about the risk of eating insects; includes belgian regulations and spanish regulations on the matter;
Again, the article is in spanish but I will try to translate the important parts for the report
http://www.20minutos.es/noticia/2382353/0/comer-insectos/riesgos-salud/espana-europa/

**Comment by ikerito7** [comment]
Very complete articule about the Insect Consumption in Mexico
Again is  in Spanish, but that is a great problem when researching latin american references. Hope Marie can check it. 

http://historia.bio.ucm.es/rsehn/cont/publis/boletines/43.pdf

**Comment by ikerito7** [comment]
Link to a company selling protein bars made from crickets

https://www.exoprotein.com

**Comment by ikerito7** [comment]
5 Companies betting on the Bud industry!
http://www.fooddive.com/news/5-food-companies-betting-on-the-bug-business/152338/

**Comment by ghost** [comment]
Thanks for all these links guys (so many stuff to read)!
Just discovered crickets were also full of Calcium thanks to them. I really should start eating some ^^

@ iker: seems that I am able to read the Spanish articles. But for now i'll just go to bed ahah.
Let's discuss how to organize it all tomorrow!

**Comment by melindatjia** [comment]
is it possible to narrow down our project? let say we discuss our project based on one class of insect, or one particular market, or one type of new technology/ method, as our base, then we go deeper (from the background and yada yada).

**Comment by Maxi1989** [comment]
@MFloru found this TED video https://www.youtube.com/watch?v=O6GimGZz6a8&spfreload=10 

_edit_ i found his slides, on the task bar on the right side there are other presentations that we can use things out of. #proudlyfoundelsewhere
